// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdHihI8yi0ZC1JP1e6hrOVXpq0SKK4r-k',
    appId: '1:1011781855873:web:369fd0d264bd8ef6b93b80',
    messagingSenderId: '1011781855873',
    projectId: 'ppb-fp-7fe30',
    authDomain: 'ppb-fp-7fe30.firebaseapp.com',
    storageBucket: 'ppb-fp-7fe30.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCggNLYJPwZiE2cHYKW62AhE-ty9o0q4aI',
    appId: '1:1011781855873:android:196b7c8bbe621a74b93b80',
    messagingSenderId: '1011781855873',
    projectId: 'ppb-fp-7fe30',
    storageBucket: 'ppb-fp-7fe30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0yZNfbSypCM43sBbTanZ2E4nwD5_ULrA',
    appId: '1:1011781855873:ios:c3599adf5f24ee7db93b80',
    messagingSenderId: '1011781855873',
    projectId: 'ppb-fp-7fe30',
    storageBucket: 'ppb-fp-7fe30.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );
}
